### ISSUE TITLE
Add field to store reference to aggregating event when an event is not processed due to aggregation/deduplication

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-esb-hook#17]
ie, 
event 1 and event 2 occur for entity foo.
Event 2 gets included in the resulting message from event 1, so event 2's status is set to duplicated / aggregated, whatever (I forget exactly).

We need a field to track where event 2 ended up getting aggregated.

If I'm not explaining this well due to rushing, @vritant knows what I'm talking about :)

**Comment by dcrissman** [comment]
Fair. So lets say we create a field called "duplicateOf" and set it as a uid. We already have a status field to indicate duplicate. Maybe if this status = 'duplicate', then duplicateOf should be set to the event _id that actually processed. Otherwise the field would essentially be null.

Sound good?

**Comment by alechenninger** [comment]
Yep, sounds right on to me
