### ISSUE TITLE
Create 'publish' entity

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-esb-hook#3]
We need to decide what fields belong in the publish entity.

UPDATED May 18, 2015 to reflect schema design changes.
UPDATED May 27, 2015 to reflect schema design changes.

Current thinking:
- _id type:uid
- entityName type:string
- versionText type:string
- CRUDOperation type:string
- identity type:object array
  - fieldText type:string
  - valueText type:string
- creationDate type:date
- createdBy type:string
- lastUpdateDate type:date
- lastUpdatedBy: type:string
- status type:string
- note type:string

**Comment by dcrissman** [comment]
Are their any additional fields that should be considered?

**Comment by bserdar** [comment]
What's createdDate?

What's status?

**Comment by dcrissman** [comment]
> What's createdDate?

The date the row (or published event if you prefer) was added to the publish entity

> What's status?

Indicates if the "mediator" (which does not exist yet) has already processed the row or not. This could also be manually toggled back to unprocessed if work needs to be re-done.

**Comment by bserdar** [comment]
So is the intend to publish to a database?

**Comment by dcrissman** [comment]
> So is the intend to publish to a database?

Correct. Then the "mediator" would poll the table for changes.

**Comment by bserdar** [comment]
Then how is this any different from audit hook?

I thought the intend was to publish to JMS.

**Comment by dcrissman** [comment]
> Then how is this any different from audit hook?

Several differences exist:
1. audit entries are intended to record the lifespan of a row of data and are primarily for informational and security purposes
2. entities that need to be audited do not necessarily need to cause an action in another system
3. publish entries are intended to be consumed (ie enum toggled)
4. publish entries will have a time to live (TTL)

**Comment by bserdar** [comment]
That still means this job can technically be done by the audit hook. All
the things you listed are traits of the data after it is published, and
don't relate to how the publishing is done. #2, #3, and #4 makes JMS more
relevant.

**Comment by dcrissman** [comment]
@bserdar how would you handle an event that needs to be re-processed?

**Comment by bserdar** [comment]
Why do you need to reprocess it? Did it fail? Then it sits in an error
queue.  It can be done the same way it does now for esb.

**Comment by bserdar** [comment]
Saving events to a DB and then processing them will introduce a delay. Is
that delay acceptable?

**Comment by dcrissman** [comment]
> Why do you need to reprocess it? Did it fail?

A requirement from the esb team, but not necessarily because of any direct failure in esb. It could simply be a re-run request from a 3rd party team. 

> It can be done the same way it does now for esb.

How does esb do it?

> Saving events to a DB and then processing them will introduce a delay. Is that delay acceptable?

A fair question. I am just joining this on-going discussion, but I know members of the esb team have been involved. I do not know if this specific concern has been raised or not.

**Comment by bserdar** [comment]
It can be done the same way it does now for esb.

>  How does esb do it?

Msg is routed to an error queue.

**Comment by jewzaam** [comment]
The requirement is to be able to bulk reprocess events.  This capability is used if there is an unexpected outage at an integrated system or for the ESB itself where it's easier to just reprocess what happened in the past instead of trying to figure out what events to trigger based on the operational (entity) data.

Another reason to keep history is for support.  It is necessary to have some history of what happened.  This could be covered by logs, but having the raw event means it is very very clear what happened.

Regarding audit, @dcrissman and I talked a bit about this @bserdar and I think audit could be used.  The major difference for audit vs publish is the data about what changed is not needed by publish.  And as noted, audit might be applied to entities that do not need published.  So, we could use audit hook to meet the requirements of publish if:
- persisting the changed data fields is optional
- underlying schema for the publish collection includes additional fields such as status and TTL index for reaping old records

Another few notes:
- /createdDate/creationDate/
- /lastUpdatedDate/lastUpdateDate/
- add createdBy
- /status/statusText/ and make it a string, not enum (leave it open, can provide context for support if it's being edited)

**Comment by dcrissman** [comment]
@jewzaam I would rather keep it as an enum so that the value cannot be arbitrarily set, potentially putting a record in an unknown state.

**Comment by jewzaam** [comment]
Disagree based on how this is used for support today, leave it open please.

**Comment by dcrissman** [comment]
How is it being used today? Should maybe it be two fields, one for status and another for context?

**Comment by dcrissman** [comment]
For now I will go with status being a text field. I will create a separate issue to discuss if it should be an enum.

**Comment by vritant** [comment]
1. entityName - change to root entity name.
2. versionText we should remove the version from this collection and control it a separate config collection.
3. CRUDOperation type:string CRUD is implied , operation is sufficient.
4. identity - I would recommend we create a separate event document for every object on the entity that changes. if the crud operation is on the simple fields, we do not need to publish the field names, it is sufficient to publish the root entity name and event key. we should replace identity with "field event key" and "field name".

fields to add:
1.priority value
2.root event key
3.headers type:object array
    name type:string
    value type:string
( additional headers to add on a message can be requested here )

**Comment by paterczm** [comment]
Reopening as requested by @vritant.

**Comment by jewzaam** [comment]
@vritant removing the version means we have no ability to transition cleanly from one version to another.  Keeping that in there we can have older events queued up with a different version while new stuff hits a newer version.  This is probably a quirky edge case that we'll not hit, but I'd like this to be considered.

Identity is for the raw event.  If you have separate entities for user and site, but want to embed site in user for integration purposes you'll need to identify the site so you can then figure out the "root" entity.  Identity serves this purpose, to identify what the event was created for.

Could you explain the use case for headers?  If it's desired, probably want to generalize the name, header is very messaging specific.

**Comment by vritant** [comment]
@jewzaam 
- ESB would not consume the version of the entity that is mentioned in the event, it would consume the version that is controlled in #12 . but it is good to document the version that was operated upon, so will add version back.
- I understand and agree, Identity is not a phrase consumers are familiar with, and what is the advantage of having an object array inplace of simple fields? personally I find consuming simple fields easier so I am suggesting we track following 4 simple fields instead of "identity"
  - root entity name ( user )
  - root event key
  - field name ( site )
  - field event key
- one use case that propped up recently is to tag events as "noop" to allow for the testing . for noop messages, mediator is required to set a noop / test header to true . we could have used the word "test" or "noop" for the field, but I had the same intent of generalizing the field name to be used for other future use cases. I suspect it is more useful to have a generic "headers" object, so the message specific-ness is intentional.
  - another potential very distant use case : support tool user requests a sync message with an invalid key, and we want to notify the user about that. there are probably better ways to handle this, but I think having a generic headers object here is useful.

latest suggestion:
-    _id type:uid
-    rootEntityName type:string
-    rootEventKey type:string
-    fieldName type:string
-    fieldEventKey type:string
-    version type:string
-    priorityValue type:integer
-    operation type:string
-    creationDate type:date
-    createdBy type:string
-    lastUpdateDate type:date
-    lastUpdatedBy: type:string
-    eventSource: type:string
-    status type:string
-    note type:string
-    headers type:object array
  -  name type:string
  -  value type:string

**Comment by vritant** [comment]
FYI @paterczm @alowens

**Comment by jewzaam** [comment]
"identity" is a lightblue term.  The mediator and publish hook are
lightblue components.  Therefore we should consider using lightblue terms
for things.  It's easy to explain what "identity" means.  It is an array
because entities in lightblue have composite keys.  The migration we're
currently working on is a perfect example, I'll shoot you an email,
@vritant, with the specifics.

**Comment by alowens** [comment]
We need to add endsystem since we are putting all events here so mediators know which ones to pick up.

**Comment by vritant** [comment]
@jewzaam publish hook is definetly a lightblue component, but I think its debatable when it comes to the mediator. mediator is a lightblue consumer, and caters to a lot of ESB requirements. we should design lightblue entities with field names that cater to the application's needs.
whether or not I am right about that, there is also an argument to be made about consistency with non-lightblue integrations and the respective event collections/ tables .

**Comment by vritant** [comment]
after discussion on email, latest suggestion:
-    _id type:uid
- entityName type:string
- rootEntityName type:string
-    rootIdentity type:object array
  - fieldText type:string
  - valueText type:string
-    identity type:object array
  - fieldText type:string
  - valueText type:string
-    endSystem type:string
-    version type:string
-    priorityValue type:integer
-    operation type:string
-    creationDate type:date
-    createdBy type:string
-    lastUpdateDate type:date
-    lastUpdatedBy: type:string
-    eventSource: type:string
-    status type:string
-    note type:string
-    headers type:object array
  -  name type:string
  -  value type:string

Edit : added entityName and rootEntityName back.

**Comment by paterczm** [comment]
Which fields will be enriched be the mediator and which are to be populated by the publishing hook?

**Comment by vritant** [comment]
@paterczm  the only fields that will be enriched by the mediator are priority value , rootIdentity ( unless publish hook has enough info to fill it ) it will however mark the status as enriched when its done

**Comment by paterczm** [comment]
What are eventSource and endSystem? How will publishing hook know those values?

**Comment by vritant** [comment]
@paterczm endSystem is the ESB end system an entity belongs to, will be read from configuration.
eventSource is who did the operation. I suspect the hook should have enough information, if not we will have to change it . I suspect audit hooks already writes this, I will take a look. while implementing.

also, please tag me so I dont have stalk this thread to look for questions :)

**Comment by dcrissman** [comment]
Re-Opening this issue.

After discussing with @vritant in #22 we found that the term "entityName" is an overridden term used in both lightblue and esb. So the "entityName" that lightblue-esb-hook currently uses refers to the esb name. I think that is confusing since everywhere else in lightblue entityName refers to the lightblue entity.

I would like to purpose the following renames:
- entityName = esbSubEntity
- rootEntityName = esbEntityName

As a follow up question, do we need the lightblue entityName to also be stored in this collection?

Thoughts? Suggestions?

**Comment by alechenninger** [comment]
What really is the difference between esb entity name just entity name? Do
they really have to be separate things? Prefixing it maybe isn't addressing
a more root problem.

Ie if I have a user entity in lightblue, and I want to integrate it, its
still a user entity. Why should that change?

"Sub" entity I can see, since you might want to publish only a portion of
an entity's document.

**Comment by dcrissman** [comment]
Firstly, the lightblue entityName and esb entityName do not necessarily match. Maybe the entity in esb is 'user', but in lightblue it is called 'person'.

The subEntityName would be like if the user had an address that got updated. So we don't want to generate an event for the entire user, but just the address.

**Comment by alechenninger** [comment]
This is interesting because currently, the determination of what the entity is as integrated in a canonical model, is done by other components in the integration flow. Ie, a camel component in the bus reads a message from a queue, it looks at the content of the message and says, "Oh this is a user", because this is where it actually starts its journey to be transformed from a "person" to a "user."

Why does the esb-hook need to know what the entity will end up as?

**Comment by alechenninger** [comment]
To be clear, I'm more curious than promoting one way or the other :)

**Comment by alechenninger** [comment]
The more I think about it, the more I think lightblue should not care what "ESB" thinks of an entity as. Let the integration components deal with the domain interchange -- that's what they're there for. To me it would make more sense if these lightblue components just concentrated on the concerns of a producing / consuming system, which shouldn't concern itself with other domain models IMHO.

**Comment by dcrissman** [comment]
> The more I think about it, the more I think lightblue should not care what "ESB" thinks of an entity as.

I agree with this statement.

@vritant @alowens @alechenninger - Since we already have the concept of headers, couldn't we just make esbRootEntityName and esbEventEntityName (or whatever we want to call them) headers? This could make the publish hook a little more generic. We would make the headers configurable on the audit hook definition in the metadata so that values could be set depending on the consuming application's needs?

I guess that does kind of leave rootIdentity in an awkward state, as it is less conducive to being a header. But I am open to suggestions.

---

>  the only fields that will be enriched by the mediator are priority value , rootIdentity

If rootIdentity (and priority) are enriched later anyway, could these live in a separate collection not managed by the publish hook, but known by the application? That means a join, but it again makes the publish hook more generic.

---

> eventSource is who did the operation. I suspect the hook should have enough information, if not we will have to change it . I suspect audit hooks already writes this, I will take a look. while implementing.

@vritant - We already have createdBy and lastUpdatedBy fields. Do you anticipate that eventSource means something else?

---

> We need to add endsystem since we are putting all events here so mediators know which ones to pick up.

I don't like the field name "endsystem", I think maybe it makes sense in an esb world, but from a lightblue perspective it I am not sure it makes sense. The only precedence for anything like this that we have is the migrator which uses a field named "consistencyCheckerName" to determine what migrator instances can act on the job. Maybe we do something similar and rename this field to "applicationName" or something?

---

Thoughts??

**Comment by dcrissman** [comment]
@vritant I see the enum Event.Status was created, I thought we had decided that an enum would be too limiting. Has that changed?

**Comment by paterczm** [comment]
I'm not in the loop on this, but I'd like to remind everyone that we recently agreed that canonical model in esb will change to match the model from lightblue. That should solve the inconsistent field names (user vs person) problems.

**Comment by alowens** [comment]
@dcrissman regarding endsystem- this is how esb defines where the message is coming from. why are we trying to change all of this now?  Design was complete awhile ago and this should look much like the event table as it is today since that is a requirement

**Comment by dcrissman** [comment]
@alowens I don't think 'endsystem' makes much sense from a lightblue perspective. That said, you are not the only person to stand by that name, so I will keep it.

**Comment by jewzaam** [comment]
@alowens the current event table does not capture the field under
discussion.  This field would store the canonical entity name.  There are
places to capture what event able has, which is the raw entity that fired
the event and the "root" entity for which an esb message will be emitted.

**Comment by vritant** [comment]
@paterczm  valid point, but I would like to specify there are more reasons to completely decouple the lightblue entity name from the ESB name for that entity:
- A current use case is that a lightblue entity will create events for two ESB entities. while there are other possible ways / work arounds to handle this ( esb could be required to create two messages every time it receives a message of that entity ), but this demonstrates the benefit of de-coupling ESB name from lightblue name . we could configure publish hook to create two events ( one with each esb entity ) if we wanted to, for the same lightblue entity.

**Comment by jewzaam** [comment]
@vritant wouldn't this be handled with logic to fire dependent events?  The
intent of the hook was to be dumb, to simply write what changed in a way
that some component (mediator) could use that to trigger the correct side
effects.

**Comment by vritant** [comment]
@jewzaam  it could be done with with the event enricher too, I agree.  I am not talking about dependent events though, this is the case where one lightblue entity is more than one ESB entity.
Note however, the implementation that we already have for hook that accomplishes this requirement is pretty dumb - basically just blindly write the entity name that is configured in the hook, no additional work is required.

**Comment by dcrissman** [comment]
I think we can safely close this now.
